import * as React from "react";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell, { tableCellClasses } from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";
import styled from "@emotion/styled";

function createData(
  vendor_code: string,
  delivery_type: string,
  product_type: string,
  title: string,
  barcode: string,
  march: number,
  april: number,
  may: number,
  june: number,
  july: number,
  abc_segment: string,
  sales_month: number,
  current_sales_fbo: number,
  current_sales_fbs: number,
  samara: number,
  remainder_mckc: number,
  remainder_rc: number,
  ads: number,
  current_idc: number,
) {
  return {
    vendor_code,
    delivery_type,
    product_type,
    title,
    barcode,
    march,
    april,
    may,
    june,
    july,
    abc_segment,
    sales_month,
    current_sales_fbo,
    current_sales_fbs,
    samara,
    remainder_mckc,
    remainder_rc,
    ads,
    current_idc,
  };
}

const rows = [
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyindfdsfsfdsfdsf...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
  createData(
    "MF47774",
    "no_text",
    "фильтры...",
    "фильтры воздушный hyin...",
    "barcode",
    0,
    0,
    0,
    3,
    0,
    "Desctop",
    0,
    0,
    0,
    3,
    1,
    10,
    0.0,
    0,
  ),
];

const TableCellUI = styled(TableCell)({
  [`&.${tableCellClasses.head}`]: {
    color: "#AAAAAA",
    fontWeight: "500",
    fontSize: "14px",
    lineHeight: "100%",
    padding: "0px 10px 3px",
    borderBottom: "1px solid white",
  },
  [`&.${tableCellClasses.body}`]: {
    fontSize: "14px",
    border: "1px solid #AAAAAA",
    minWidth: "90px",
    maxWidth: "170px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    padding: " 12px 5px 4px",
  },
});
const TableRowUI = styled(TableRow)({
  "&:first-child": {
    borderTop: "1px solid white",
  },
  "&:last-child td, &:last-child th": {
    border: "1px solid #AAAAAA",
    borderBottom: "none",
  },
});

const Yandex = () => {
  return (
    <TableContainer component={Paper}>
      <Table sx={{ minWidth: 650 }} aria-label="simple table">
        <TableHead>
          <TableRow>
            <TableCellUI>Артикул</TableCellUI>
            <TableCellUI>Тип Доставки</TableCellUI>
            <TableCellUI>Тип товара</TableCellUI>
            <TableCellUI>Название</TableCellUI>
            <TableCellUI>Штрихкод</TableCellUI>
            <TableCellUI>Март</TableCellUI>
            <TableCellUI>Апрель</TableCellUI>
            <TableCellUI>Май</TableCellUI>
            <TableCellUI>Июнь</TableCellUI>
            <TableCellUI>Июль</TableCellUI>
            <TableCellUI>ABC Segment (beta)</TableCellUI>
            <TableCellUI>Продажи в текущем месяце</TableCellUI>
            <TableCellUI>Текущие продажи(F BO)</TableCellUI>
            <TableCellUI>
              Текущие
              <br />
              продажи(F
              <br />
              BS )
            </TableCellUI>
            <TableCellUI>Самара</TableCellUI>
            <TableCellUI>Остаток МСКС (шт)</TableCellUI>
            <TableCellUI>Остаток РЦ (шт)</TableCellUI>
            <TableCellUI>ADS</TableCellUI>
            <TableCellUI>Текущий IDC (по складу в днях)</TableCellUI>
          </TableRow>
        </TableHead>
        <TableBody>
          {rows.map((row) => (
            <TableRowUI
              key={row.vendor_code}
              sx={{ "&:last-child td, &:last-child th": { border: 0 } }}>
              <TableCellUI component="th" scope="row">
                {row.vendor_code}
              </TableCellUI>
              <TableCellUI>{row.delivery_type}</TableCellUI>
              <TableCellUI>{row.product_type}</TableCellUI>
              <TableCellUI>{row.title}</TableCellUI>
              <TableCellUI>{row.barcode}</TableCellUI>
              <TableCellUI align="right">{row.march}</TableCellUI>
              <TableCellUI align="right">{row.april}</TableCellUI>
              <TableCellUI align="right">{row.may}</TableCellUI>
              <TableCellUI align="right">{row.june}</TableCellUI>
              <TableCellUI align="right">{row.july}</TableCellUI>
              <TableCellUI>{row.abc_segment}</TableCellUI>
              <TableCellUI align="right">{row.sales_month}</TableCellUI>
              <TableCellUI align="right">{row.current_sales_fbo}</TableCellUI>
              <TableCellUI align="right">{row.current_sales_fbs}</TableCellUI>
              <TableCellUI align="right">{row.samara}</TableCellUI>
              <TableCellUI align="right">{row.remainder_mckc}</TableCellUI>
              <TableCellUI align="right">{row.remainder_rc}</TableCellUI>
              <TableCellUI align="right">{row.ads}</TableCellUI>
              <TableCellUI align="right">{row.current_idc}</TableCellUI>
            </TableRowUI>
          ))}
        </TableBody>
      </Table>
    </TableContainer>
  );
};

export default React.memo(Yandex);
